language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.7.7
matrix:
  exclude:
   - python: "2.6"
     env: DJANGO_VERSION=1.7.7
install: pip install -q Django==$DJANGO_VERSION djangorestframework
script: python setup.py test
